### ISSUE TITLE
Fix reduce

### ISSUE THREAD

**Issue by vbjay** [ZdsAlpha/Fraction#3]
Reduce will create a fraction of 3/1 out of 22/7.  

``` VB
    Public Sub ReduceCreatesWrongFraction()
        Dim f As New Fraction(Math.PI)

        Dim num As BigInteger = f.Numerator
        Dim dem As BigInteger = f.Denominator

        Do
            num = f.Numerator
            dem = f.Denominator
            Trace.WriteLine(f.DisplayDetails)
            f.Reduce(2)
        Loop Until (num = f.Numerator AndAlso dem = f.Denominator) OrElse f.IsUndefined
        Trace.WriteLine(f.DisplayDetails)
    End Sub
```

![image](https://cloud.githubusercontent.com/assets/3629489/14784108/f0759dfc-0ac1-11e6-94f7-e3b3c9057bf4.png)

**Comment by ZdsAlpha** [comment]
It is actually not an issue. Reduce function is to get nearest but more reduced fraction.  User himself has to specify how much fraction has to be reduced.
Reduction process only stops if proper fraction of given fraction is zero or further reductions results in zero or undefined.
Changes:
I have added another condition reduction will stop if further reduction results denominator 1.
This will solve the problem.

**Comment by ZdsAlpha** [comment]
But it will not fix what you are asking for. An example is 22/7 is approaching to 22/8 or 21/7 which will be reduced as 11/4 and 3/1.
The simple solution you have to specify yourself how much fraction is to be reduced. 3.14159265358979 is not equal to 22/7 but approaches to 22/7.
I have undone the last changes. Because they are causing more problems. Because now 22/7 will be simplified as 11/4 which is equal to 2.75 while 3/1 = 3.0 is more accurate.

**Comment by vbjay** [comment]
It would reduce to 3 1/7.

Whole Number 3
Numerator 1
Denominator 7

## 

**NOT**
Whole Number 3
Numerator 3
Denominator 1

**Comment by ZdsAlpha** [comment]
You are taking numerator of fraction not its proper fraction.
A fraction is sum of its WholeNumber and ProperFraction. Get numerator and denominator of its proper fraction.
